backend/backend/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from cbrf_files.views import deposits_xml

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^For_CBRF/Deposits.xml', deposits_xml),
    url(r'^captcha/', include('captcha.urls')),
]

urlpatterns += i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^feedback/', include('feedback.urls')),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

backend/feedback/urls.py
from django.conf.urls import url
from views import FeedbackCreate
from django.views.generic import TemplateView


urlpatterns = [
    url(r'add/$', FeedbackCreate.as_view(), name='feedback-add'),
    url(r'^success/$', TemplateView.as_view(template_name="feedback/success.html"), name='feedback-success'),
]

backend/cbrf_files/models.py
from django.db import models


class CBRF_Deposit(models.Model):
    uploaded_date = models.DateTimeField(auto_now_add=True)
    photo = models.FileField(upload_to='cbrf_deposit')

backend/feedback/models.py
# -*- coding: utf-8 -*-
import os
import uuid
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import truncatewords
from django.utils.encoding import python_2_unicode_compatible


def update_filename(instance, filename):
    path = "upload/path/"
    ext = filename.rsplit('.')[1]
    fn = unicode(uuid.uuid4())
    return "{0}/{1}.{2}".format(path, fn, ext)


class Receiver(models.Model):
    name = models.CharField(_('name'), max_length=100)
    email = models.EmailField(_('e-mail'))

    def __unicode__(self):
        return self.name


class Theme(models.Model):
    name = models.CharField(_('name'), max_length=100)
    receivers = models.ManyToManyField(Receiver)

    def __unicode__(self):
        return self.name


@python_2_unicode_compatible
class Feedback(models.Model):
    theme = models.ForeignKey(Theme)
    name = models.CharField(_('name'), max_length=100)
    email = models.EmailField(_('e-mail'))
    body = models.TextField(_("message"))
    file1 = models.FileField(upload_to=update_filename, null=True, blank=True)
    file2 = models.FileField(upload_to=update_filename, null=True, blank=True)
    file3 = models.FileField(upload_to=update_filename, null=True, blank=True)

    ip = models.CharField(max_length=50, null=True, blank=True)
    sent_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _("feedback")
        verbose_name_plural = _("feedbacks")

    def __str__(self):
        return truncatewords(self.body, 16)

    def __unicode__(self):
        return truncatewords(self.body, 16)

backend/feedback/forms.py
from django import forms
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string

from captcha.fields import CaptchaField

from models import Feedback, Receiver


class FeedbackModelForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Feedback
        fields = ['theme', 'name', 'email', 'body', 'file1', 'file2', 'file3']

    def send_email(self):
        template_html = 'feedback/new_feedback_email.html'
        template_text = 'feedback/new_feedback_email.txt'
        theme = self.cleaned_data['theme']
        receivers = Receiver.objects.filter(theme=theme).values_list('email', flat=True)
        from_email = settings.DEFAULT_FROM_EMAIL
        subject = u"{0}:{1}".format(theme.name, self.cleaned_data['name'])
        text_content = render_to_string(template_text, {'obj': self.instance})
        html_content = render_to_string(template_html, {'obj': self.instance})
        msg = EmailMultiAlternatives(subject, text_content, from_email, receivers)
        msg.attach_alternative(html_content, "text/html")
        for i in range(1, 4):
            file_object = self.cleaned_data['file1']
            try:
                msg.attach(file_object.name, file_object.read(), file_object.content_type)
            except:
                pass
        msg.send()

backend/cbrf_files/views.py
from django.http import HttpResponse
from StringIO import StringIO
from cbrf_files.models import CBRF_Deposit
import os, mimetypes, urllib

def deposits_xml(request):
    header = CBRF_Deposit.objects.order_by('?')[0]
    image = StringIO(file(header.photo.path, "rb").read())
    return HttpResponse(image.read(), content_type='application/xml')

backend/feedback/views.py
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse
from models import Feedback
from forms import FeedbackModelForm

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

class FeedbackCreate(CreateView):
    model = Feedback
    form_class = FeedbackModelForm
    template_name = 'feedback/add.html'

    def get_success_url(self):
        return reverse('feedback-success')

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.instance.ip = get_client_ip(self.request)
        form.send_email()
        return super(FeedbackCreate, self).form_valid(form)

backend/backend/templates/about_us/about_us.html
{% extends "base.html" %}

{% load cms_tags staticfiles sekizai_tags menu_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}


{% block content %}

    {% include 'top-menu.html' %}

    <div class="container-fluid corp-page-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 col-md-8 col-sm-7 col-xs-12">

                    <ul class="breadcrums">
                        {% show_breadcrumb "partials/breadcrumb.html" %}
                    </ul>

                    {% placeholder "content" %}

                </div>

                <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12 aside-block">
                    <div class="row"><h3>Курсы валют <a href="#" class="blue">2 сентября 2015</a></h3>
                    <span>Доллар США </span><span>24,12 / 25,40</span><br>
                    <span>Евро </span><span>21,19 / 22,69</span><br></div>
                    <aside>
                        <ul>
                            <li><a href="#"><img src="{% static "img/icn_user.png" %}" alt="" width="22px"><span>Частным клиентам</span></a></li>
                            <li><a href="#"><img src="{% static "img/icn_wallet.png" %}" alt="" width="22px"><span>Кредитным<br>организациям</span></a></li>
                            <li><a href="#"><img src="{% static "img/icn_card.png" %}" alt="" width="22px"><span>Пластиковые карты</span></a></li>
                            <li><a href="#"><img src="{% static "img/icn_online.png" %}" alt="" width="22px"><span>РББ.Онлайн</span></a></li>
                            <li><a href="#"><img src="{% static "img/icn_vault.png" %}" alt="" width="22px"><span>Индивидуальные сейфы</span></a></li>
                            <li><a href="#"><img src="{% static "img/icn_case.png" %}" alt="" width="22px"><span>Бланки и документы</span></a></li>
                            <li><a href="#"><img src="{% static "img/Icn_tariff.png" %}" alt="" width="22px"><span>Тарифы</span></a></li>
                            <li><a href="#"><img src="{% static "img/icn_realty.png" %}" alt="" width="22px"><span>Реализация залогового<br>имущества</span></a></li>
                        </ul>
                    </aside>
                </div>

            </div>
        </div>
    </div>

{% endblock content %}

backend/backend/templates/base.html
{% load cms_tags staticfiles sekizai_tags menu_tags cbr_rates %}{% cms_toolbar %}
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}РББ{% endblock title %}</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/css/bootstrap.min.css">

        <link rel="apple-touch-icon" sizes="57x57" href={% static "img/apple-icon-57x57.png" %}>
	<link rel="apple-touch-icon" sizes="60x60" href={% static "img/apple-icon-60x60.png" %}>
	<link rel="apple-touch-icon" sizes="72x72" href={% static "img/apple-icon-72x72.png" %}>
	<link rel="apple-touch-icon" sizes="76x76" href={% static "img/apple-icon-76x76.png" %}>
	<link rel="apple-touch-icon" sizes="114x114" href={% static "img/apple-icon-114x114.png" %}>
	<link rel="apple-touch-icon" sizes="120x120" href={% static "img/apple-icon-120x120.png" %}>
	<link rel="apple-touch-icon" sizes="144x144" href={% static "img/apple-icon-144x144.png" %}>
	<link rel="apple-touch-icon" sizes="152x152" href={% static "img/apple-icon-152x152.png" %}>
	<link rel="apple-touch-icon" sizes="180x180" href={% static "img/apple-icon-180x180.png" %}>
	<link rel="icon" type="image/png" sizes="192x192"  href={% static "img/android-icon-192x192.png" %}>
	<link rel="icon" type="image/png" sizes="32x32" href={% static "img/favicon-32x32.png" %}>
	<link rel="icon" type="image/png" sizes="96x96" href={% static "img/favicon-96x96.png" %}>
	<link rel="icon" type="image/png" sizes="16x16" href={% static "img/favicon-16x16.png" %}>
	<link rel="manifest" href={% static "img/manifest.json" %}>
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-TileImage" content={% static "img/ms-icon-144x144.png" %}>
	<meta name="theme-color" content="#ffffff">


        <link href={% static "css/styles.css" %} rel="stylesheet">



        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=latin,cyrillic" rel="stylesheet" type="text/css">
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        {% render_block "css" %}
        <script>
            jQuery(document).ready(function(){
                jQuery('.left_popup .ttl .title').click(function(){
                    jQuery('.left_popup').toggleClass('open');
                });
            });
        </script>
    </head>

    <body>
    {% block banner %}
       <div class="left_popup">
        <div class="inner">
            {% static_placeholder "banner" %}
        </div>
        <div class="ttl">
            <div class="icon"></div>
            <div class="title">{% static_placeholder "txt_for_btn_banner" %}</div>
        </div>
    </div>
    {% endblock banner %}
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
	    
	      ga('create', 'UA-85881796-1', 'auto');
	        ga('send', 'pageview');
		
     </script>
		
{#    {% get_cbr_rates as cbr_rates %}#}

        <div class="wrap_inner">

        {% block content %}{% endblock content %}
        </div>

        {% include "partials/footer.html" %}

        {% include "partials/scripts.html" %}

        {% render_block "js" %}


    </body>
</html>

backend/backend/templates/corporate_cliens/corporate_cliens.html
{% extends "base.html" %}

{% load cms_tags staticfiles sekizai_tags menu_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}


{% block content %}

    {% include 'top-menu.html' %}

    <div class="container-fluid corp-page-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 col-md-8 col-sm-7 col-xs-12">

                    <ul class="breadcrums">
                        {% show_breadcrumb "partials/breadcrumb.html" %}
                    </ul>

                    {% show_menu_below_id "corporate_cliens" %}

                    {% placeholder "content" %}

                </div>

                <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12 aside-block">
                    {% include 'partials/menu.html' %}
                </div>

            </div>
        </div>
    </div>

{% endblock content %}

backend/backend/templates/feature.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    <div class="jumbotron">
        {% placeholder "feature" %}
    </div>
    <div>
        {% placeholder "content" %}
    </div>
{% endblock content %}

backend/backend/templates/feedback/add.html
{% extends "base.html" %}

{% load i18n cms_tags staticfiles sekizai_tags menu_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}


{% block content %}

    {% include 'top-menu.html' %}
<style>
id_file2
</style>
    <div class="container-fluid corp-page-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 col-md-8 col-sm-7 col-xs-12">

                    <ul class="breadcrums">
                        {% show_breadcrumb "partials/breadcrumb.html" %}
                    </ul>

                    <form enctype="multipart/form-data"  method="POST" action="{% url "feedback-add" %}" id="feedback_form" class="form-horizontal">
                        {%  csrf_token %}
                        {% for field in form %}
                          {% if not field.name in 'file2, file3'  %}
                        <div class="form-group">
                            {{ field.errors }}
                        <div class="col-sm-2">
                           {% if field.name in 'theme'  %}
                              <label for="id_theme">Тема:</label>
                           {% else %}
                             {{ field.label_tag }}
                           {% endif %}

                        </div>
                         <div class="col-sm-6">
                            {{ field }}
                         </div>
                          {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                          {% endif %}
                        </div>
                        {% endif %}
                        {% endfor %}
		    <input type="hidden" name="user_ip" value="{{ request.META.REMOTE_ADDR|default:"" }}">
                    <button type="submit" form="feedback_form" value="Submit">Submit</button>
                    </form>

                </div>

            </div>
        </div>
    </div>
{% endblock content %}

backend/backend/templates/feedback/new_feedback_email.html
От: {{ obj.name }} -> {{ obj.email }}<br>
IP: {{ obj.ip }}<br>

<br>
{{ obj.body }}

backend/backend/templates/feedback/success.html
{% extends "base.html" %}

{% load cms_tags staticfiles sekizai_tags menu_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}


{% block content %}

    {% include 'top-menu.html' %}

    <div class="container-fluid corp-page-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 col-md-8 col-sm-7 col-xs-12">

                    <ul class="breadcrums">
                        {% show_breadcrumb "partials/breadcrumb.html" %}
                    </ul>

                    <p>Ваше сообщение успешно отправлено!</p>

                </div>

            </div>
        </div>
    </div>

{% endblock content %}

backend/backend/templates/forms-and-documents/forms-and-documents.html
{% extends "base.html" %}

{% load cms_tags staticfiles sekizai_tags menu_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}


{% block content %}

    {% include 'top-menu.html' %}

    <div class="container-fluid corp-page-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 col-md-8 col-sm-7 col-xs-12">

                    <ul class="breadcrums">
                        {% show_breadcrumb "partials/breadcrumb.html" %}
                    </ul>

                    {% show_menu_below_id "forms-and-documents" %}

                    {% placeholder "content" %}

                </div>

                <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12 aside-block">
                    {% include 'partials/menu.html' %}
                </div>

            </div>
        </div>
    </div>

{% endblock content %}

backend/backend/templates/implementation-collateral-property/implementation-collateral-property.html
{% extends "base.html" %}

{% load cms_tags staticfiles sekizai_tags menu_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}


{% block content %}

    {% include 'top-menu.html' %}

    <div class="container-fluid corp-page-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 col-md-8 col-sm-7 col-xs-12">

                    <ul class="breadcrums">
                        {% show_breadcrumb "partials/breadcrumb.html" %}
                    </ul>

                    {% show_menu_below_id "implementation-collateral-property" %}

                    {% placeholder "content" %}

                </div>

                <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12 aside-block">
                    {% include 'partials/menu.html' %}
                </div>

            </div>
        </div>
    </div>

{% endblock content %}

backend/backend/templates/info_about_max_dep_indiv.html
{% extends "base.html" %}

{% load cms_tags staticfiles sekizai_tags menu_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}


{% block content %}
{% include "top-menu.html" %}


    <div class="container-fluid corp-page-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 col-md-8 col-sm-7 col-xs-12">

                    <ul class="breadcrums">
                        {% show_breadcrumb "partials/breadcrumb.html" %}
                    </ul>

{#                    {% placeholder "content" %}#}

                    <h3>Информация о максимальных процентных ставках по вкладам физических лиц<br />
                        за <span id="DocDate"></span></h3>

                    <p>Наименование кредитной организации -ПАО АРКБ &#39;Росбизнесбанк&#39;<br />
                        Регистрационный номер кредитной организации - 1405<br />
                        &nbsp;</p>

                    <table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" class="table table-bordered">
                      <tbody>
                        <tr>
                          <td colspan="7">По срокам вкладов согласно заключенным договорам с физическими лицами в российских рублях (в процентах)</td>
                        </tr>
                        <tr>
                          <td>До востребования</td>
                          <td>На срок до 90 дней</td>
                          <td>На срок от 91 до 180 дней</td>
                          <td>На срок от 181 до 1 года</td>
                          <td>На срок свыше 1 года</td>
                        </tr>
                        <tr>
                          <td id="DepositsRubCallDep"></td>
                          <td id="DepositsRubDep90"></td>
                          <td id="DepositsRubDep91-180"></td>
                          <td id="DepositsRubDep181-1"></td>
                          <td id="DepositsRubDep1up"></td>
                        </tr>
                            </tbody>
                        </table>

                        <p><br />
                        &nbsp;</p>

                        <table class="table table-bordered">
                            <tbody>
                                <tr>
                                    <td colspan="7">По срокам вкладов согласно заключенным договорам с физическими лицами в долларах США (в процентах)</td>
                                </tr>
                                <tr>
                                    <td>До востребования</td>
                                    <td>На срок до 90 дней</td>
                                    <td>На срок от 91 до 180 дней</td>
                                    <td>На срок от 181 до 1 года</td>
                                    <td>На срок свыше 1 года</td>
                                </tr>
                                <tr>
                          <td id="DepositsUSDCallDep"></td>
                          <td id="DepositsUSDDep90"></td>
                          <td id="DepositsUSDDep91-180"></td>
                          <td id="DepositsUSDDep181-1"></td>
                          <td id="DepositsUSDDep1up"></td>
                                </tr>
                            </tbody>
                        </table>

                        <p><br />
                        &nbsp;</p>

                        <table class="table table-bordered">
                            <tbody>
                                <tr>
                                    <td colspan="7">По срокам вкладов согласно заключенным договорам с физическими лицами в евро (в процентах)</td>
                                </tr>
                                <tr>
                                    <td>До востребования</td>
                                    <td>На срок до 90 дней</td>
                                    <td>На срок от 91 до 180 дней</td>
                                    <td>На срок от 181 до 1 года</td>
                                    <td>На срок свыше 1 года</td>
                                </tr>
                                <tr>
                          <td id="DepositsEurCallDep"></td>
                          <td id="DepositsEurDep90"></td>
                          <td id="DepositsEurDep91-180"></td>
                          <td id="DepositsEurDep181-1"></td>
                          <td id="DepositsEurDep1up"></td>
                                </tr>
                            </tbody>
                        </table>

                        <p>&nbsp;</p>


                </div>

                <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12 aside-block">

                    {% include 'partials/menu.html' %}

                </div>

            </div>
        </div>
    </div>

    {% addtoblock "js" %}
<script>

  function renderXml(xmlDOC){
      $('#DocDate').html($(xmlDOC).find('CredOrgDepRate').attr('DocDate'));

      $('#DepositsRubCallDep').html($(xmlDOC).find('DepositsRub').find('CallDep'));
      $('#DepositsRubDep90').html($(xmlDOC).find('DepositsRub').find('Dep90'));
      $('#DepositsRubDep91-180').html($(xmlDOC).find('DepositsRub').find('Dep91-180'));
      $('#DepositsRubDep181-1').html($(xmlDOC).find('DepositsRub').find('Dep181-1'));
      $('#DepositsRubDep1up').html($(xmlDOC).find('DepositsRub').find('Dep1up'));

      $('#DepositsUSDCallDep').html($(xmlDOC).find('DepositsUSD').find('CallDep'));
      $('#DepositsUSDDep90').html($(xmlDOC).find('DepositsUSD').find('Dep90'));
      $('#DepositsUSDDep91-180').html($(xmlDOC).find('DepositsUSD').find('Dep91-180'));
      $('#DepositsUSDDep181-1').html($(xmlDOC).find('DepositsUSD').find('Dep181-1'));
      $('#DepositsUSDDep1up').html($(xmlDOC).find('DepositsUSD').find('Dep1up'));

      $('#DepositsEurCallDep').html($(xmlDOC).find('DepositsEur').find('CallDep'));
      $('#DepositsEurDep90').html($(xmlDOC).find('DepositsEur').find('Dep90'));
      $('#DepositsEurDep91-180').html($(xmlDOC).find('DepositsEur').find('Dep91-180'));
      $('#DepositsEurDep181-1').html($(xmlDOC).find('DepositsEur').find('Dep181-1'));
      $('#DepositsEurDep1up').html($(xmlDOC).find('DepositsEur').find('Dep1up'));

    }


function getXml(url){
  var result = "";
  var xml = new XMLHttpRequest();

  xml.open("GET", url, true);
  xml.onreadystatechange = function () {
    if (xml.readyState == 4 && xml.status == 200)
    {
      var result = xml.responseXML;
      renderXml(xml.responseXML);
    }
  };
    xml.send(null);
}

$(document).ready(function () {
    getXml('/For_CBRF/Deposits.xml');
});


</script>
{% endaddtoblock "js" %}


{% endblock content %}

backend/backend/templates/menu.html
{% load i18n menu_tags cache staticfiles %}

    {% for child in children %}
        <li class="{% if child.ancestor %}ancestor{% endif %}
{#            {% if child.selected %} active{% endif %}#}
            {% if child.children %} dropdown{% endif %}">
            {% if child.children %}
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="toggle">
                    {{ child.get_menu_title }}
                </a>
                <ul class="dropdown-menu">
                    <li class="dropdown-deco"><img src={% static "img/dropdown.png" %} alt=""></li>
                    {% show_menu from_level to_level extra_inactive extra_active template "" "" child %}
                </ul>
            {% else %}
                <a href="{{ child.get_absolute_url }}"><span>{{ child.get_menu_title }}</span></a>
            {% endif %}
        </li>
        {% if class and forloop.last and not forloop.parentloop %}{% endif %}
    {% endfor %}

backend/backend/templates/offices.html
{% extends "base.html" %}

{% load cms_tags staticfiles sekizai_tags menu_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}


{% block content %}
{% include 'top-menu.html' %}

    <div class="container-fluid corp-page-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 col-md-8 col-sm-7 col-xs-12">

                    <ul class="breadcrums">
                        {% show_breadcrumb "partials/breadcrumb.html" %}
                    </ul>
<iframe width="100%" height="500" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps/ms?ie=UTF8&amp;msa=0&amp;msid=115453948435209999388.000496f945f28e4c7417a&amp;ll=55.72711,37.597961&amp;spn=0.386675,0.769043&amp;z=10&amp;output=embed"></iframe>
                    {% placeholder "content" %}

                </div>

                <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12 aside-block">
                   {% include 'partials/menu.html' %}
                </div>

            </div>
        </div>
    </div>

{% endblock content %}

backend/backend/templates/page.html
{% extends "base.html" %}

{% load cms_tags staticfiles sekizai_tags menu_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}


{% block content %}
{% include "top-menu.html" %}


    <div class="container-fluid corp-page-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 col-md-8 col-sm-7 col-xs-12">

                    <ul class="breadcrums">
                        {% show_breadcrumb "partials/breadcrumb.html" %}
                    </ul>

                    {% placeholder "content" %}

                </div>

                <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12 aside-block">

                    {% include 'partials/menu.html' %}

                </div>

            </div>
        </div>
    </div>

{% endblock content %}

backend/backend/templates/partials/breadcrumb.html
{% for ance in ancestors %}
<li>
  {% if not forloop.first %}
    {% if not forloop.last %}
        <a href="{{ ance.get_absolute_url }}">{{ ance.get_menu_title }}</a> /
    {% else %}
        {{ ance.get_menu_title }}
    {% endif %}
  {% endif %}
</li>
{% endfor %}

backend/backend/templates/partials/scripts.html
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/js/bootstrap.min.js"></script>

backend/backend/templates/partials/styles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>